"""empty message

Revision ID: 060805f96748
Revises: d61fc1eb8abd
Create Date: 2021-07-27 16:55:54.080694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060805f96748'
down_revision = 'd61fc1eb8abd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prefer', 'food_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prefer', sa.Column('food_address', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
