"""empty message

Revision ID: 1cead99eb86d
Revises: c4970f03bdc7
Create Date: 2021-07-21 13:48:24.809845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cead99eb86d'
down_revision = 'c4970f03bdc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.Text(), nullable=True),
    sa.Column('food_category', sa.Text(), nullable=True),
    sa.Column('food_address', sa.Text(), nullable=True),
    sa.Column('time_save', sa.DateTime(), nullable=True),
    sa.Column('curr_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('good',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.Text(), nullable=True),
    sa.Column('food_category', sa.Text(), nullable=True),
    sa.Column('food_address', sa.Text(), nullable=True),
    sa.Column('time_save', sa.DateTime(), nullable=True),
    sa.Column('curr_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('food_name', sa.TEXT(), nullable=True),
    sa.Column('food_category', sa.TEXT(), nullable=True),
    sa.Column('food_address', sa.TEXT(), nullable=True),
    sa.Column('time_save', sa.DATETIME(), nullable=True),
    sa.Column('curr_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('good')
    op.drop_table('bad')
    # ### end Alembic commands ###
