"""empty message

Revision ID: 90f88f2a6f15
Revises: 1cead99eb86d
Create Date: 2021-07-27 15:31:10.844027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f88f2a6f15'
down_revision = '1cead99eb86d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prefer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.Text(), nullable=True),
    sa.Column('food_category', sa.Text(), nullable=True),
    sa.Column('food_address', sa.Text(), nullable=True),
    sa.Column('time_save', sa.DateTime(), nullable=True),
    sa.Column('curr_time', sa.DateTime(), nullable=True),
    sa.Column('preference', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('good')
    op.drop_table('bad')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bad',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('food_name', sa.TEXT(), nullable=True),
    sa.Column('food_category', sa.TEXT(), nullable=True),
    sa.Column('food_address', sa.TEXT(), nullable=True),
    sa.Column('time_save', sa.DATETIME(), nullable=True),
    sa.Column('curr_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('good',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('food_name', sa.TEXT(), nullable=True),
    sa.Column('food_category', sa.TEXT(), nullable=True),
    sa.Column('food_address', sa.TEXT(), nullable=True),
    sa.Column('time_save', sa.DATETIME(), nullable=True),
    sa.Column('curr_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('prefer')
    # ### end Alembic commands ###
