"""empty message

Revision ID: c4970f03bdc7
Revises: 
Create Date: 2021-07-16 20:24:42.189126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4970f03bdc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.Text(), nullable=True),
    sa.Column('food_category', sa.Text(), nullable=True),
    sa.Column('food_address', sa.Text(), nullable=True),
    sa.Column('time_save', sa.DateTime(), nullable=True),
    sa.Column('curr_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###
