"""empty message

Revision ID: d61fc1eb8abd
Revises: 90f88f2a6f15
Create Date: 2021-07-27 16:11:53.896185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61fc1eb8abd'
down_revision = '90f88f2a6f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.Text(), nullable=True),
    sa.Column('food_category', sa.Text(), nullable=True),
    sa.Column('food_number', sa.Text(), nullable=True),
    sa.Column('image_name', sa.Text(), nullable=True),
    sa.Column('render_file', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food')
    # ### end Alembic commands ###
