"""empty message

Revision ID: f10b35233950
Revises: 
Create Date: 2021-07-30 17:54:34.925706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f10b35233950'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.Text(), nullable=True),
    sa.Column('food_category', sa.Text(), nullable=True),
    sa.Column('food_number', sa.Text(), nullable=True),
    sa.Column('image_name', sa.Text(), nullable=True),
    sa.Column('render_file', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prefer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.Text(), nullable=True),
    sa.Column('food_category', sa.Text(), nullable=True),
    sa.Column('image_name', sa.Text(), nullable=True),
    sa.Column('time_save', sa.DateTime(), nullable=True),
    sa.Column('curr_time', sa.DateTime(), nullable=True),
    sa.Column('preference', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prefer')
    op.drop_table('food')
    # ### end Alembic commands ###
