"""empty message

Revision ID: 70bfe5fb23aa
Revises: a70e12dc13dc
Create Date: 2021-07-27 21:51:24.654296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70bfe5fb23aa'
down_revision = 'a70e12dc13dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imgname', sa.String(length=64), nullable=False),
    sa.Column('imgdata', sa.LargeBinary(), nullable=False),
    sa.Column('rendered_data', sa.Text(), nullable=False),
    sa.Column('pic_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###
